# FastQC options
fastqc_opts: "--noextract -t 4"

# fastp options
fastp_opts: "--adapter_sequence NNNNNNNNNNNNNNNNNNNN --adapter_sequence GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG -c -q 20 -u 50 -n 15 -5 20 -3 20 -w 1 -l 75"


