# Reference genome
ref_genome: /path/to/reference/genome.fa

# Annotation file
annotation_file: /path/to/annotation.gtf

# FastQC options
fastqc_opts: "--noextract -t 4"

# fastp options
fastp_opts: "--adapter_sequence NNNNNNNNNNNNNNNNNNNN --adapter_sequence GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG -c -q 20 -u 50 -n 15 -5 20 -3 20 -w 1 -l 75"

# BWA options
bwa_opts: "-t 4"

# Samtools options
samtools_opts: ""

# GATK options
gatk_opts: ""

# Picard options
picard_opts: ""

# Freebayes options
freebayes_opts: "--pooled-continuous"

# Number of threads
threads: 8

# Minimum mapping quality
mapq: 30

# Minimum base quality
baseq: 20

# Minimum coverage
min_coverage: 10

# Minimum variant frequency
min_freq: 0.01

# Output directories
raw_data_dir: raw_data
aligned_data_dir: aligned_data
vcf_dir: vcf_files
